version: '3.7'

services:
  backend:
    build: .
    container_name: node_backend
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    ports:
     - "${PORT}:${PORT}"
    env_file:
      - ./.env
    environment:
      - MIN_MOVIE_COUNT=${MIN_MOVIE_COUNT}
      - MAX_MOVIE_COUNT=${MAX_MOVIE_COUNT}
  mysql:
    container_name: ${MYSQL_HOST}
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}


networks:
  default:
    external:
      name: movie_app